//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_TP_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_Esclarecimento
    {
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public string descricao { get; set; }
    
        public virtual Utilizador Utilizador { get; set; }
        public virtual Utilizador Utilizador1 { get; set; }
    }
}
